-- ⚠️ DEPRECATED — do NOT run this file.
--
-- This was the original localStorage-era prototype schema with PERMISSIVE
-- "allow all (using true)" RLS policies. That is the OPPOSITE of the security
-- model the imarketin platform now uses.
--
-- The canonical, secure, multi-tenant schema lives in:
--     supabase/migrations/0001_imarketin_platform.sql
--
-- It enforces RLS deny-by-default, tenant isolation via location_id, and
-- role-based access (manager/staff) via JWT app_metadata claims.
--
-- See docs/sprints/2026-06-09_supabase-integration.md for the full design,
-- the access-code → scoped-session auth flow, and the proof-of-done log.
